# Generated by Django 2.2.7 on 2019-11-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлентворительно'), (2, 'Плохо'), (1, 'Очень плохо')], default=5, verbose_name='Оценка'),
        ),
    ]
